---
title: "Untitled"
author: '@jrcajide'
date: "9/4/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
library(data.table)

# The following two commands remove any previously installed H2O packages for R.
if ("package:h2o" %in% search()) { detach("package:h2o", unload=TRUE) }
if ("h2o" %in% rownames(installed.packages())) { remove.packages("h2o") }

# Next, we download packages that H2O depends on.
if (! ("methods" %in% rownames(installed.packages()))) { install.packages("methods") }
if (! ("statmod" %in% rownames(installed.packages()))) { install.packages("statmod") }
if (! ("stats" %in% rownames(installed.packages()))) { install.packages("stats") }
if (! ("graphics" %in% rownames(installed.packages()))) { install.packages("graphics") }
if (! ("RCurl" %in% rownames(installed.packages()))) { install.packages("RCurl") }
if (! ("jsonlite" %in% rownames(installed.packages()))) { install.packages("jsonlite") }
if (! ("tools" %in% rownames(installed.packages()))) { install.packages("tools") }
if (! ("utils" %in% rownames(installed.packages()))) { install.packages("utils") }

# Now we download, install and initialize the H2O package for R.
install.packages("h2o", type="source", repos=(c("http://h2o-release.s3.amazonaws.com/h2o/rel-ueno/3/R")))

library(h2o)

h2o.init(ip = "46.101.126.146")
h2o.init(ip = "127.0.0.1")

```

## H2O Web interface
```{r}
browseURL("http://46.101.126.146:54321/flow/index.html")
```


```{r}
wnb.hex = h2o.uploadFile(path = "./data/wnb.csv", destination_frame = "wnb.hex")
```

```{r}
wnb.hex$C1 <- NULL
```

```{r}
summary(wnb.hex)
```

```{r}
wnb.split <- h2o.splitFrame(data = wnb.hex, ratios = 0.75)
```

```{r}
# Creates training set from 1st data set in split
wnb.train <- wnb.split[[1]]
# Creates testing set from 2st data set in split
wnb.test <- wnb.split[[2]]
```

```{r}
head(wnb.train)
```

```{r}
Y = "Class"
X = setdiff(names(wnb.train), "Class")
```

```{r}
wnb.glm <- h2o.glm(training_frame=wnb.train, x=X, y=Y, family = "binomial", alpha = 0.5)
```

```{r}
summary(wnb.glm)
```
```{r}
h2o.varimp(wnb.glm)
```

```{r}
# Predict using GLM model
pred = h2o.predict(object = wnb.glm, newdata = wnb.test)
# Look at summary of predictions: probability of TRUE class (p1)
summary(pred)
```

```{r}
h2o.auc(wnb.glm)
```

```{r}
h2o.confusionMatrix(object = wnb.glm, threshold = 0.3)
```

```{r}
auc <- h2o.auc(wnb.glm, valid = TRUE)
fpr <- h2o.fpr( h2o.performance(wnb.glm, valid = F) )[['fpr']]
tpr <- h2o.tpr( h2o.performance(wnb.glm, valid = F) )[['tpr']]
ggplot( data.table(fpr = fpr, tpr = tpr), aes(fpr, tpr) ) + 
geom_line() + theme_bw() + ggtitle( sprintf('AUC: %f', auc) )
```


```{r}
h2o.download_pojo(wnb.glm, getwd())
```


```{r}
system("curl -X POST --data '{travelers: 2, avg_session_duration: 0}' 46.101.126.146:2373/predict")
```


```{r}
system("curl -X POST --data-binary @data/wnb_new_data.json  46.101.126.146:2373/predict", wait = T)
```


#### GBM

```{r}
wnb.gbm <- h2o.gbm(y = 1, x = 2:5, training_frame = wnb.train, ntrees = 10,
                    max_depth = 3,min_rows = 2, learn_rate = 0.2, distribution= "gaussian")

# To obtain the Mean-squared Error by tree from the model object:
wnb.gbm@model$scoring_history
```

```{r}
perf <- h2o.performance(wnb.gbm, newdata = wnb.test)
print(perf)
```

```{r}
pred_hf <- h2o.predict(wnb.gbm, newdata = wnb.test)
head(pred_hf)
```

```{r}
plot(wnb.glm)
```



